# const placeholder module

TK_WIN_WIDTH = 800
TK_WIN_HEIGHT = 800
TK_UPDATE_TIMER = 1000

TK_BG_COLOR         = '#ffffff'
TK_BG_STICKS_COLOR  = '#000000'
TK_COLOR_BLACK      = '#000000'
TK_COLOR_SKYBLUE    = '#33ccff'
TK_COLOR_YELLOW     = '#ffff00'
TK_COLOR_VIOLET     = '#ff00ff'
TK_COLOR_ORANGE     = '#ff9933'
TK_COLOR_BLUE       = '#0000ff'
TK_COLOR_RED        = '#ff0000'
TK_COLOR_GREEN      = '#00ff00'

TK_RDM_COLORS = [TK_COLOR_GREEN, TK_COLOR_RED, TK_COLOR_BLUE, TK_COLOR_ORANGE,
                 TK_COLOR_VIOLET, TK_COLOR_YELLOW, TK_COLOR_SKYBLUE]
